language: objective-c
osx_image: xcode8.3
cache: cocoapods
before_install:
  - gem install cocoapods
  - pod install
xcode_workspace: CarTrackApp.xcodeworkspace
xcode_scheme: CarTrackApp
xcode_sdk: iphonesimulator10.3  
script:
  xcodebuild -workspace CarTrackApp.xcworkspace -list
  xcodebuild -workspace CarTrackApp.xcworkspace -scheme CarTrackApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' test