language: swift
osx_image: xcode8.3
cache: cocoapods
before_install:
- gem install cocoapods
- pod install
xcode_project: CarTrackApp.xcodeworkspace
xcode_scheme: CarTrackApp
xcode_sdk: iphonesimulator10.3
script:
  build.sh