language: swift
osx_image: xcode8.3
cache: cocoapods
before_install:
- gem install cocoapods
- pod install
script:
- set -o pipefail && xcodebuild test -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

xcode_project: CarTrackApp.xcodeworkspace
xcode_scheme: CarTrackApp
xcode_sdk: iphonesimulator10.3