language: objective-c
osx_image: xcode8.3
cache: cocoapods
before_install:
  - gem install cocoapods
  - pod install
xcode_workspace: CarTrackApp.xcodeworkspace
xcode_scheme: CarTrackAppTests
xcode_sdk: iphonesimulator10.3  